name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Ativa o cache automático para downloads do uv
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: |
          uv sync --frozen --no-dev # Instala o projeto
          uv pip install pytest pytest-cov # Garante ferramentas de teste

      - name: Run Tests
        run: |
          uv run pytest --cov=src tests/
